image: alpine

before_script:
  - apk --no-cache add py3-sphinx_rtd_theme make
  - pip3 install sphinx

pages:
  stage: deploy
  script:
  - cd docs
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
    - master
